
// the onload call back, should be called when the page is loaded into the browser
window.onload = () => {
    // I added this log to make sure the function is called
    console.log('loaded');
    // call the static function to get the places
    let places = staticLoadPlaces();
    // call the render function to render the places
    renderPlaces(places);
};

// this function return the GPS location for the places
// the return value is an array of objects, containing the name, latitude and longitude
function staticLoadPlaces() {
    return [
        {
            name: 'MyModel',
            location: {
                lat: 31,
                lng: 121,
            }
        },
    ];
}

// this function render the places to the map
// the places is an array of objects, containing the name, latitude and longitude
// the places is generated by the staticLoadPlaces function
function renderPlaces(places) {
    // create a new scene DOM
    let scene = document.querySelector('a-scene');
    // for each place in the places array, create a new marker
    places.forEach((place) => {
        // I added this log to check the content of the input
        console.log(place);
        // get the latitude and longitude value
        let latitude = place.location.lat;
        let longitude = place.location.lng;

        // create a new entity DOM
        let model = document.createElement('a-entity');
        // set the position of the entity
        model.setAttribute('gps-entity-place', `latitude: ${latitude}; longitude: ${longitude};`);
        // set the model of the entity
        model.setAttribute('gltf-model', './assets/MyModel/scene.gltf');
        // set the rotation of the entity 
        model.setAttribute('rotation', '0 180 0');
        // set the animation of the entity
        model.setAttribute('animation-mixer', '');
        // set the scale of the entity
        model.setAttribute('scale', '0.5 0.5 0.5');
        // add a new event listener to the entity, so that we can listen to the load event
        model.addEventListener('loaded', () => {
            window.dispatchEvent(new CustomEvent('gps-entity-place-loaded'))
        });
        // add the entity to the scene
        scene.appendChild(model);
        // I added this log to check the added element
        console.log(scene);
    });
}
